-- La cobertura del paciente pasa de un dato que nadie guarda a una tabla.
--
-- Cecilia atiende por obra social y son setenta convenios. Hasta hoy el sistema
-- no sabía nada de eso: el paciente reservaba y ella se enteraba de bajo qué
-- concepto venía recién cuando lo tenía sentado en el sillón.
--
-- Para qué sirve el dato, que es lo que define la forma de la tabla: que el
-- paciente y ella sepan ANTES del turno bajo qué concepto se sacó, si esa obra
-- social se atiende, y si va como particular. No es un dato de facturación.
--
-- `nombre` guarda la fila de Cecilia tal cual, sin depurar ni renombrar.
-- `entidad` es una columna aparte que sólo dice bajo qué título se agrupa la
-- fila en el desplegable del paciente: para cincuenta y cuatro filas es igual
-- al nombre, y sólo cinco entidades tienen más de un plan. Se agrupa porque los
-- planes de una misma entidad no son equivalentes, y quien elige mal viaja,
-- llega y ahí se entera de que el suyo no le cubre el tratamiento.
--
-- Va una sola tabla y no dos porque la entidad hoy no tiene ni un dato propio:
-- es sólo un nombre. El día que tenga uno -- un teléfono de autorizaciones, una
-- marca de convenio caído -- partirla en dos es una migración chica.

create table public.obras_sociales (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  nombre text not null unique,
  entidad text not null,
  activa boolean not null default true
);

-- `nombre` es único porque el desplegable lo muestra tal cual: dos filas con el
-- mismo texto son dos opciones idénticas en la lista y el paciente no tiene
-- forma de elegir bien. Las setenta de Cecilia son setenta textos distintos,
-- verificado antes de escribir esta línea.
--
-- `activa` sigue la regla del proyecto: un convenio que se cae se apaga, no se
-- borra. Una fila borrada dejaría turnos viejos apuntando a algo que ya no
-- existe, y el turno tiene que poder decir siempre bajo qué concepto se sacó.
--
-- RLS se enciende de forma explícita porque las tablas creadas por SQL no la
-- traen activada, a diferencia de las creadas desde el panel.

alter table public.obras_sociales enable row level security;

grant select on public.obras_sociales to service_role;
