-- El modelo pasa de una profesional implícita a varias explícitas.
--
-- Hasta hoy el sistema daba por sentado que atendía una sola persona, pero ese
-- supuesto no estaba escrito en ninguna tabla: `horarios_base` no decía de quién
-- eran esos horarios y `turnos` no decía con quién era el turno. Entran
-- profesionales que alquilan consultorio, cada uno con su agenda y con los
-- tratamientos que sabe hacer.
--
-- Se hace antes de la primera reserva real, que es el momento barato: una
-- columna vacía cuesta minutos; la misma columna con turnos de pacientes
-- adentro obliga a decidir a mano de quién era cada turno viejo.
--
-- `profesional_tratamientos` es una tabla de unión: un profesional hace muchos
-- tratamientos y un tratamiento lo hacen muchos profesionales. Esa relación no
-- entra como columna en ninguna de las dos tablas — necesita una tabla propia
-- cuyo único trabajo es guardar la pareja.
--
-- RLS se enciende de forma explícita porque las tablas creadas por SQL no la
-- traen activada, a diferencia de las creadas desde el panel. Las siete tablas
-- del proyecto tienen que quedar parejas.


create table public.profesionales (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  nombre text not null,
  apellido text not null,
  email text not null unique,
  activo boolean not null default true,
  fecha_baja timestamptz
);

-- `email` es obligatorio acá y opcional en `pacientes`: es el canal por el que
-- se le avisan sus turnos, así que un profesional sin email no se puede dar de
-- alta. Y es único: un correo personal por persona, sin dos filas para la misma.
--
-- `fecha_baja` es redundante con `activo` a propósito. `created_at` ya guarda
-- cuándo entró y `activo` dice si sigue, pero nadie guardaba CUÁNDO se fue: sin
-- esta columna el panel puede decir "de baja" y no "de baja el 12-ago-2026". Se
-- acepta la redundancia porque las dos las escribe una sola acción, nunca un
-- humano tipeando. Si algún día importa el ir y venir de alguien que se va y
-- vuelve, el camino limpio es enganchar una tabla de eventos, no tocar ésta.

alter table public.profesionales enable row level security;

grant select on public.profesionales to service_role;


create table public.profesional_tratamientos (
  id bigint generated by default as identity primary key,
  profesional_id bigint not null references public.profesionales (id) on delete restrict,
  tratamiento_id bigint not null references public.tratamientos (id) on delete restrict,
  unique (profesional_id, tratamiento_id)
);

-- `on delete restrict` en las dos: si alguien intenta borrar un profesional o un
-- tratamiento que todavía está en uso, la base lo frena. Es la regla del
-- proyecto — no se borran filas, se apaga el estado.
--
-- La pareja es única. Nadie carga dos veces el mismo tratamiento a propósito,
-- pero un doble clic o una carga repetida sí lo hacen, y como esta tabla es el
-- filtro que decide qué profesionales ve el paciente, una pareja duplicada lo
-- muestra dos veces en la lista.

alter table public.profesional_tratamientos enable row level security;

grant select on public.profesional_tratamientos to service_role;
